<?php

use Drupal\image\Entity\ImageStyle;
use Drupal\node\NodeInterface;
/**
 * Implements hook_theme().
 */
function welcome_module_theme($existing, $type, $theme, $path) {
  return [
    'movie_card' => [
      'variables' => [
        'title' => "",
        'description' => "",
        'image' => ""
      ],
    ],
  ];
}


function welcome_module_node_update(NodeInterface $node) {
  if ($node->bundle()=="blog_post") {
    //dump($node);
    if (!$node->isNew() && $node->original->get('field_blog_post_type')->target_id == NULL
      && $node->get('field_blog_post_type')->target_id != NULL) {
      $term = $node->get('field_blog_post_type')->entity;
      $term->get('field_counter')
        ->setValue($term->get('field_counter')->value + 1);
      $term->save();
    }
    elseif (!$node->isNew() && $node->original->get('field_blog_post_type')->target_id != NULL
      && $node->get('field_blog_post_type')->target_id == NULL) {
      $term = $node->original->get('field_blog_post_type')->entity;
      $term->get('field_counter')
        ->setValue($term->get('field_counter')->value - 1);
      $term->save();
    }
    elseif (
      $node->get('field_blog_post_type')->target_id !=
      $node->original->get('field_blog_post_type')->target_id) {
      $term = $node->get('field_blog_post_type')->entity;
      $term->get('field_counter')
        ->setValue($term->get('field_counter')->value + 1);
      $term->save();
      $term = $node->original->get('field_blog_post_type')->entity;
      $term->get('field_counter')
        ->setValue($term->get('field_counter')->value - 1);
      $term->save();
    }
  }
}

//function welcome_module_node_delete(NodeInterface $node){
//  $term = $node->get('field_blog_post_type')->entity;
//  $term->get('field_counter')->setValue($term->get('field_counter')->value - 1);
//  $term->save();
//}

function welcome_module_node_insert(NodeInterface $node){
  if ($node->bundle()=="blog_post") {
    if (!$node->get('field_blog_post_type')->isEmpty()) {
      $term = $node->get('field_blog_post_type')->entity;
      $term->get('field_counter')
        ->setValue($term->get('field_counter')->value + 1);
      $term->save();
    }
  }
}

function welcome_module_preprocess_node__blog_post__teaser(&$variables) {
//  dump($variables);
//  die;
  /** @var \Drupal\node\Entity\Node $node */
  $node = $variables['node'];
  $img = "";
  if (!empty($node->field_image->entity)){
    $img = ImageStyle::load('large')->buildUrl($node->field_image->entity->getFileUri());
  }
  $variables["card"] = [
    "#theme" => "movie_card",
    '#title' => $node->get('title')->value,
    '#description' => $node->get('body')->getValue()[0]["value"],
    '#image' => $img,
    '#date' => date("Y/m/d")
  ];
}


